# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gui2(object):
    def setupUi(self, gui2):
        gui2.setObjectName("gui2")
        gui2.resize(1366, 720)
        self.label = QtWidgets.QLabel(gui2)
        self.label.setGeometry(QtCore.QRect(6, 10, 1361, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../GUI MATERIAL/ExtraGui/Jarvis_Gui (2).gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_Strat = QtWidgets.QPushButton(gui2)
        self.pushButton_Strat.setGeometry(QtCore.QRect(250, 660, 141, 31))
        self.pushButton_Strat.setStyleSheet(" \n"
"background-color: rgb(0, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.pushButton_Strat.setObjectName("pushButton_Strat")
        self.pushButton_Exit = QtWidgets.QPushButton(gui2)
        self.pushButton_Exit.setGeometry(QtCore.QRect(410, 660, 171, 31))
        self.pushButton_Exit.setStyleSheet(" \n"
"background-color: rgb(0, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.pushButton_Exit.setObjectName("pushButton_Exit")

        self.retranslateUi(gui2)
        QtCore.QMetaObject.connectSlotsByName(gui2)

    def retranslateUi(self, gui2):
        _translate = QtCore.QCoreApplication.translate
        gui2.setWindowTitle(_translate("gui2", "Dialog"))
        self.pushButton_Strat.setText(_translate("gui2", "START"))
        self.pushButton_Exit.setText(_translate("gui2", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gui2 = QtWidgets.QDialog()
    ui = Ui_gui2()
    ui.setupUi(gui2)
    gui2.show()
    sys.exit(app.exec_())
