# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(1401, 859)
        self.bg_1 = QtWidgets.QLabel(JarvisUI)
        self.bg_1.setGeometry(QtCore.QRect(0, 0, 1381, 871))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("../GUI MATERIAL/B.G/Black_Template.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(JarvisUI)
        self.bg_2.setGeometry(QtCore.QRect(10, 30, 471, 331))
        self.bg_2.setStyleSheet("background-color: rgb(74, 255, 255);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(JarvisUI)
        self.bg_3.setGeometry(QtCore.QRect(500, 30, 581, 331))
        self.bg_3.setStyleSheet("background-color: rgb(74, 255, 255);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.Gif_1 = QtWidgets.QLabel(JarvisUI)
        self.Gif_1.setGeometry(QtCore.QRect(20, 50, 441, 291))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("C:/Users/KALPIT VORA/Desktop/5a9628b9256d9e54afd861edc949b0f2_w200.webp"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(JarvisUI)
        self.Gif_2.setGeometry(QtCore.QRect(510, 40, 561, 311))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("../GUI MATERIAL/ExtraGui/61de57a229cd6901f83fe0f9d04b5dca_w200.webp"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(JarvisUI)
        self.Gif_3.setGeometry(QtCore.QRect(-100, 330, 661, 431))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("../GUI MATERIAL/VoiceReg/__1.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.bg_5 = QtWidgets.QLabel(JarvisUI)
        self.bg_5.setGeometry(QtCore.QRect(1090, 30, 261, 161))
        self.bg_5.setStyleSheet("background-color: rgb(74, 255, 255);")
        self.bg_5.setText("")
        self.bg_5.setObjectName("bg_5")
        self.Gif_4 = QtWidgets.QLabel(JarvisUI)
        self.Gif_4.setGeometry(QtCore.QRect(1100, 40, 241, 141))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("../GUI MATERIAL/ExtraGui/Earth.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.bg_6 = QtWidgets.QLabel(JarvisUI)
        self.bg_6.setGeometry(QtCore.QRect(1090, 620, 291, 231))
        self.bg_6.setText("")
        self.bg_6.setPixmap(QtGui.QPixmap("../GUI MATERIAL/B.G/gyhf.jpg"))
        self.bg_6.setScaledContents(True)
        self.bg_6.setObjectName("bg_6")
        self.Texttime_2 = QtWidgets.QTextBrowser(JarvisUI)
        self.Texttime_2.setGeometry(QtCore.QRect(1120, 750, 241, 91))
        self.Texttime_2.setStyleSheet("background-color: Transparent;\n"
" border-radius:none;")
        self.Texttime_2.setObjectName("Texttime_2")
        self.Texttime_1 = QtWidgets.QTextBrowser(JarvisUI)
        self.Texttime_1.setGeometry(QtCore.QRect(1120, 630, 231, 81))
        self.Texttime_1.setStyleSheet("background-color: Transparent;\n"
" border-radius:none;")
        self.Texttime_1.setObjectName("Texttime_1")
        self.pushButton_Strat = QtWidgets.QPushButton(JarvisUI)
        self.pushButton_Strat.setGeometry(QtCore.QRect(1100, 210, 241, 61))
        self.pushButton_Strat.setStyleSheet(" \n"
"background-color: rgb(0, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.pushButton_Strat.setObjectName("pushButton_Strat")
        self.bg_7 = QtWidgets.QLabel(JarvisUI)
        self.bg_7.setGeometry(QtCore.QRect(1090, 200, 261, 161))
        self.bg_7.setStyleSheet("background-color: rgb(74, 255, 255);")
        self.bg_7.setText("")
        self.bg_7.setObjectName("bg_7")
        self.pushButton_Exit = QtWidgets.QPushButton(JarvisUI)
        self.pushButton_Exit.setGeometry(QtCore.QRect(1100, 290, 241, 61))
        self.pushButton_Exit.setStyleSheet(" \n"
"background-color: rgb(0, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.bg_8 = QtWidgets.QLabel(JarvisUI)
        self.bg_8.setGeometry(QtCore.QRect(1090, 400, 291, 231))
        self.bg_8.setText("")
        self.bg_8.setPixmap(QtGui.QPixmap("../GUI MATERIAL/B.G/gyhf.jpg"))
        self.bg_8.setScaledContents(True)
        self.bg_8.setObjectName("bg_8")
        self.Texttime_3 = QtWidgets.QTextBrowser(JarvisUI)
        self.Texttime_3.setGeometry(QtCore.QRect(1120, 530, 241, 81))
        self.Texttime_3.setStyleSheet("background-color: Transparent;\n"
" border-radius:none;\n"
"")
        self.Texttime_3.setObjectName("Texttime_3")
        self.Texttime_4 = QtWidgets.QTextBrowser(JarvisUI)
        self.Texttime_4.setGeometry(QtCore.QRect(1110, 410, 241, 81))
        self.Texttime_4.setStyleSheet("background-color: Transparent;\n"
"border-radius:none;")
        self.Texttime_4.setObjectName("Texttime_4")
        self.pushButton_yt = QtWidgets.QPushButton(JarvisUI)
        self.pushButton_yt.setGeometry(QtCore.QRect(500, 370, 131, 61))
        self.pushButton_yt.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_yt.setObjectName("pushButton_yt")
        self.pushButton__cm = QtWidgets.QPushButton(JarvisUI)
        self.pushButton__cm.setGeometry(QtCore.QRect(700, 370, 131, 61))
        self.pushButton__cm.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton__cm.setObjectName("pushButton__cm")
        self.pushButton_wp = QtWidgets.QPushButton(JarvisUI)
        self.pushButton_wp.setGeometry(QtCore.QRect(890, 370, 131, 61))
        self.pushButton_wp.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton_wp.setObjectName("pushButton_wp")
        self.label = QtWidgets.QLabel(JarvisUI)
        self.label.setGeometry(QtCore.QRect(510, 590, 531, 311))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../GUI MATERIAL/ExtraGui/initial.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(JarvisUI)
        self.label_2.setGeometry(QtCore.QRect(530, 470, 461, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../GUI MATERIAL/ExtraGui/Jarvis_Gui (1).gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.bg_1.raise_()
        self.Gif_3.raise_()
        self.bg_2.raise_()
        self.bg_3.raise_()
        self.Gif_1.raise_()
        self.Gif_2.raise_()
        self.bg_5.raise_()
        self.Gif_4.raise_()
        self.bg_6.raise_()
        self.Texttime_2.raise_()
        self.Texttime_1.raise_()
        self.bg_7.raise_()
        self.pushButton_Strat.raise_()
        self.pushButton_Exit.raise_()
        self.bg_8.raise_()
        self.Texttime_3.raise_()
        self.Texttime_4.raise_()
        self.pushButton_yt.raise_()
        self.pushButton__cm.raise_()
        self.pushButton_wp.raise_()
        self.label.raise_()
        self.label_2.raise_()

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "Dialog"))
        self.pushButton_Strat.setText(_translate("JarvisUI", "START"))
        self.pushButton_Exit.setText(_translate("JarvisUI", "EXIT"))
        self.pushButton_yt.setText(_translate("JarvisUI", "Youtube"))
        self.pushButton__cm.setText(_translate("JarvisUI", "Chrome"))
        self.pushButton_wp.setText(_translate("JarvisUI", "Whatsapp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QDialog()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
