# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainjarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1366, 736)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1371, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../GUI MATERIAL/ExtraGui/Jarvis_Gui (2).gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_Strat = QtWidgets.QPushButton(Dialog)
        self.pushButton_Strat.setGeometry(QtCore.QRect(240, 670, 141, 31))
        self.pushButton_Strat.setStyleSheet(" \n"
"background-color: rgb(0, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.pushButton_Strat.setObjectName("pushButton_Strat")
        self.pushButton_Exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_Exit.setGeometry(QtCore.QRect(380, 670, 141, 31))
        self.pushButton_Exit.setStyleSheet(" \n"
"background-color: rgb(0, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(500, 300, 781, 371))
        self.frame.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 10, 761, 361))
        self.plainTextEdit.setAutoFillBackground(True)
        self.plainTextEdit.setStyleSheet(" background-color: Transparent;\n"
"  \n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 181, 16))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QPlainTextEdit(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 711, 281))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(85, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(40, 330, 711, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(85, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_Strat_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_Strat_2.setGeometry(QtCore.QRect(670, 340, 71, 16))
        self.pushButton_Strat_2.setStyleSheet(" \n"
"background-color: rgb(0, 0, 0);\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.pushButton_Strat_2.setObjectName("pushButton_Strat_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_Strat.setText(_translate("Dialog", "START"))
        self.pushButton_Exit.setText(_translate("Dialog", "UNMUTE"))
        self.frame.setAccessibleDescription(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#55ffff;\">Terminal Output :</span></p></body></html>"))
        self.plainTextEdit.setAccessibleName(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Terminal output :</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "TERMINAL OUTPUT :"))
        self.pushButton_Strat_2.setText(_translate("Dialog", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
