# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
 
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1496, 918)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(9, 9, 1440, 900))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../GUI MATERIAL/ExtraGui/live.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_Strat = QtWidgets.QPushButton(Dialog)
        self.pushButton_Strat.setGeometry(QtCore.QRect(1150, 690, 241, 61))
        self.pushButton_Strat.setStyleSheet(" \n"
"background-color: rgb(0, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.pushButton_Strat.setObjectName("pushButton_Strat")
        self.pushButton_Exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_Exit.setGeometry(QtCore.QRect(1150, 770, 241, 61))
        self.pushButton_Exit.setStyleSheet(" \n"
"background-color: rgb(0, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);")
        self.pushButton_Exit.setObjectName("pushButton_Exit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_Strat.setText(_translate("Dialog", "START"))
        self.pushButton_Exit.setText(_translate("Dialog", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
